from datetime import datetime
import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"

# Per-state county FIPS lookup, generated by generate_counties.py into
# backend/data/counties/<state>.json (e.g. "az.json", "co.json"). Loaded
# lazily and cached, so adding a new state's file doesn't require any
# code change here -- just call compare_snapshots(..., state="az").
_state_fips_cache = {}


def _load_state_fips(state_abbr):

    state_abbr = state_abbr.lower()

    if state_abbr in _state_fips_cache:
        return _state_fips_cache[state_abbr]

    path = DATA_DIR / "counties" / f"{state_abbr}.json"

    if not path.exists():
        _state_fips_cache[state_abbr] = {}
        return {}

    with open(path) as f:
        raw = json.load(f)

    # Raw shape: {"04013": {"name":..., "slug":..., ...}, ...} -- re-key
    # by slug, since that's what county keys in the election data use.
    by_slug = {entry["slug"]: fips for fips, entry in raw.items()}

    _state_fips_cache[state_abbr] = by_slug

    return by_slug


def compare_snapshots(old, new, state="co"):
    # No previous snapshot exists
    if old is None:
        return {
            "timestamp": datetime.now().isoformat(),
            "counties": {},
            "has_changes": False,
            "has_counties": True,
            "first_run": True
        }

    if not old.get("region_results"):

        old_votes = {}
        new_votes = {}
        new_meta = {}

        results = {
            "candidates": {}
        }

        has_changes = False


        for candidate in old["candidates"]:
            old_votes[candidate["name"]] = candidate["votes"]

        for candidate in new["candidates"]:
            new_votes[candidate["name"]] = candidate["votes"]
            new_meta[candidate["name"]] = {
                "party": candidate.get("party"),
                "color": candidate.get("color")
            }

        batch_total = 0

        for candidate in new_votes:
            vote_change = new_votes[candidate] - old_votes.get(candidate, 0)

            batch_total += vote_change

            if vote_change != 0:
                has_changes = True

            results["candidates"][candidate] = {
                "change": vote_change,
                "votes": new_votes[candidate],
                **new_meta[candidate]
            }


        batch = batch_sort(results,batch_total)


        results["batch"] = {
            "total": batch_total,
            **batch
        }

        return {
            "timestamp": datetime.now().isoformat(),
            "results": results,
            "has_changes": has_changes,
            "has_counties": False,
            "first_run": False
        }

    has_changes = False
    time_stamp = datetime.now().isoformat()

    comparison = {
        "timestamp": time_stamp,
        "candidates": [
            {
                "name": c["name"],
                "party": c.get("party"),
                "color": c.get("color")
            }
            for c in new.get("candidates", [])
        ],
        "counties": {},
        "has_changes": False,
        "has_counties": True,
    }



    old_regions = old.get("region_results", {})
    new_regions = new.get("region_results", {})

    # Union, not just old's keys -- otherwise a county that's brand new
    # (not in the previously saved snapshot) silently never appears in
    # the output, no matter how much real data comes in for it.
    all_counties = set(old_regions) | set(new_regions)

    for county in all_counties:

        if county not in new_regions:
            # County existed before but the live source no longer has it
            # (e.g. dropped/renamed) -- skip rather than showing stale
            # data as if it were current.
            continue

        new_county = new_regions[county]
        old_county = old_regions.get(county, {"percent_reporting": None, "candidates": []})

        # Create a shortcut so we don't keep typing the long lookup
        comparison["counties"][county] = {}
        county_data = comparison["counties"][county]

        # `new_county` may already carry its own fips/name -- from
        # civicapi directly, or from the county_providers aggregator,
        # which sets these from registry.py. Only fall back to the
        # (Colorado-only) COUNTY_FIPS lookup if neither source has it,
        # e.g. for older civicapi county keys that rely on the slug match.
        county_data["name"] = (
            new_county.get("name")
            or county.replace("_", " ").title()
        )
        county_data["fips"] = new_county.get("fips") or _load_state_fips(state).get(county)
        # ---------------- Reporting ----------------

        old_reporting = old_county.get("percent_reporting")
        new_reporting = new_county.get("percent_reporting")

        county_data["reporting"] = {
            "old": old_reporting,
            "new": new_reporting,
            "change": (
                new_reporting - old_reporting
                if old_reporting is not None and new_reporting is not None
                else None
            )
        }

        if new_reporting is not None and new_reporting != old_reporting:
            has_changes = True

        # ---------------- Candidates ----------------

        county_data["candidates"] = {}
        old_votes = {}
        new_votes = {}
        new_meta = {}

        for candidate in old_county["candidates"]:
            old_votes[candidate["name"]] = candidate["votes"]

        for candidate in new_county["candidates"]:
            new_votes[candidate["name"]] = candidate["votes"]
            new_meta[candidate["name"]] = {
                "party": candidate.get("party"),
                "color": candidate.get("color")
            }

        # Union, not just old's keys -- otherwise a brand-new candidate
        # (not in the previously saved snapshot) never appears at all,
        # the same class of bug as the county-level one above.
        all_candidates = set(old_votes) | set(new_votes)

        for candidate in all_candidates:

            vote_change = new_votes.get(candidate, 0) - old_votes.get(candidate, 0)

            if vote_change != 0:
                has_changes = True

            county_data["candidates"][candidate] = {
                "change": vote_change,
                "votes": new_votes.get(candidate, old_votes.get(candidate, 0)),
                **new_meta.get(candidate, {"party": None, "color": None})
            }
        # ---------------- Batch Total ----------------

        batch_total = 0

        for candidate_data in county_data["candidates"].values():
            batch_total += candidate_data["change"]

        # ---------------- Current County Leader ----------------

        sorted_candidates = sorted(
            new_county["candidates"],
            key=lambda c: c["votes"],
            reverse=True
        )

        leader = sorted_candidates[0]
        runner_up = sorted_candidates[1] if len(sorted_candidates) > 1 else None

        total_votes = sum(c["votes"] for c in new_county["candidates"])

        margin_votes = leader["votes"] - runner_up["votes"] if runner_up else leader["votes"]

        county_data["leader"] = {
            "name": leader["name"],
            "votes": leader["votes"],
            "party": leader.get("party"),
            "color": leader.get("color"),
            "margin_votes": margin_votes,
            "margin_percent": (
                margin_votes / total_votes
                if total_votes else 0
            )
        }

        # ---------------- Batch Sorting ----------------

        batch = batch_sort(county_data, batch_total)

        county_data["batch"] = {
            "total": batch_total,
            **batch,
        }

    comparison["has_changes"] = has_changes


    return comparison


def batch_sort(data, batch_total):
    candidates = data["candidates"]

    candidates_sorted = sorted(
        candidates.items(),
        key=lambda item: item[1]["change"],
        reverse=True
    )

    if len(candidates_sorted) < 2:
        return {
            "winner": candidates_sorted[0][0] if candidates_sorted else None,
            "margin_votes": 0,
            "margin_percent": 0,
        }

    leader_name, leader_data = candidates_sorted[0]
    _, second_data = candidates_sorted[1]

    batch_margin_votes = leader_data["change"] - second_data["change"]

    batch_margin_percent = (
        batch_margin_votes / batch_total if batch_total else 0
    )

    for candidate_data in candidates.values():
        candidate_data["batch_percent"] = (
            candidate_data["change"] / batch_total
            if batch_total else 0
        )

    return {
        "winner": leader_name,
        "margin_votes": batch_margin_votes,
        "margin_percent": batch_margin_percent,
    }